### ISSUE TITLE
Sort CODEOWNERS alphabetically

### ISSUE THREAD

**Issue by milind-shakya-sp** [milin/gitown#3]
* gitown version: master
* Python version: 3.6.8
* Operating System: Linux CentOS

### Description

Right now the `gitown` tool just appends new items to the CODEOWNERS file irrespective of sorting.
This works fine for smaller teams, but teams of larger size that have multiple pull requests to the project everyday, it can very well cause merge conflicts, due to frequently updated CODEOWNERS.

One way  to minimize the conflicts is keep the CODEOWNERS file automatically sorted automatically.

**Comment by davidsneighbour** [comment]
I would say just add a pre-commit setup AFTER the gitown setup that uses the sort file procedure from here: 

https://github.com/pre-commit/pre-commit-hooks#file-contents-sorter

That should help?

**Comment by milind-shakya-sp** [comment]
Possibly. I haven't used the `file-contents-sorter` hook but if that's works the way am thinking, I think that should do the trick. 

This would however still need at-least some documentation and an entry to the ReadMe.
